version: '3'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./temp/dev/mysql/data/:/var/lib/mysql/:rw
    environment:
      MYSQL_DATABASE: smartlock
      MYSQL_USER: smartlock
      MYSQL_PASSWORD: smartlock
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/:rw
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/:ro
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "client_host=172.22.0.1"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/hosts:/etc/nginx/conf.d/:ro
      - ./temp/dev/nginx/logs:/var/log/nginx/:rw
    links:
      - php

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - /temp/dev/certbot/logs:/var/log/letsencrypt
