version: '3'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./temp/dev/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: smartlock
      MYSQL_USER: smartlock
      MYSQL_PASSWORD: smartlock
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/opt/app
      - ./temp/dev/php/logs:/var/log/php
