version: '3'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./temp/dev/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: smartlock
      MYSQL_USER: smartlock
      MYSQL_PASSWORD: smartlock
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
      - ./temp/dev/php/logs:/var/log/php
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "client_host=172.22.0.1"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./temp/dev/nginx/logs:/var/log/nginx
    links:
      - php
