version: '3'

services:
  mysql:
    image: mysql:8
    volumes:
      - ./temp/dev/mysql/data/:/var/lib/mysql/:rw
    environment:
      MYSQL_DATABASE: smartlock
      MYSQL_USER: smartlock
      MYSQL_PASSWORD: smartlock
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "127.0.0.1:3306:3306"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/:rw
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "client_host=172.22.0.1"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"

  cron:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: ["crond", "-f", "-d", "8"]
    restart: unless-stopped
    volumes:
      - ./:/var/www/:rw
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/:ro

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/hosts:/etc/nginx/conf.d/:ro
      - ./temp/dev/nginx/logs:/var/log/nginx/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - php

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - /temp/dev/certbot/logs:/var/log/letsencrypt
