parameters:
  beds24.apikey: '%env(BEDS24_APIKEY)%'
  beds24.propkey: '%env(BEDS24_PROPKEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Controller\ApiController: ~
  App\Services\ScienerApi: ~
  App\Services\LockService: ~
  App\Services\BookingService: ~

  App\Providers\Beds24\Client\ClientV1:
    class: App\Providers\Beds24\Client\ClientV1
    arguments:
      - '@GuzzleHttp\ClientInterface'
      - '%beds24.apikey%'
      - '%beds24.propkey%'

  GuzzleHttp\Client: ~
  GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'
