parameters:
  beds24.apikey: '%env(BEDS24_APIKEY)%'
  beds24.token: '%env(BEDS24_DIGEST_TOKEN)%'
  beds24.props:
    156799: '%env(BEDS24_PROP_APARTMENTS)%'
    156424: '%env(BEDS24_PROP_GUESTHOUSE)%'
    156798: '%env(BEDS24_PROP_HOSTEL)%'
    159459: '%env(BEDS24_PROP_TEST)%'

  mysql.host: '%env(MYSQL_HOST)%'
  mysql.db: '%env(MYSQL_DB)%'
  mysql.user: '%env(MYSQL_USER)%'
  mysql.pass: '%env(MYSQL_PASS)%'
  mysql.charset: 'utf8mb4'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  App\Controller\ApiController:
    class: App\Controller\ApiController
    arguments:
      - '@App\Services\LockService'
      - '@App\Services\BookingService'
      - '%beds24.token%'
  App\Providers\Beds24\Client\ClientV1:
    class: App\Providers\Beds24\Client\ClientV1
    arguments:
      - '@GuzzleHttp\ClientInterface'
      - '%beds24.apikey%'
  App\Repository\TokenMysqlRepository:
    class: App\Repository\TokenMysqlRepository
    arguments:
      - '@PDO'
  App\Services\BookingService:
    class: App\Services\BookingService
    arguments:
      - '@App\Providers\Beds24\Client\ClientV1'
      - '%beds24.props%'
  App\Services\LockService: ~
  App\Services\ScienerApi: ~
  App\Repository\TokenRepositoryInterface: '@App\Repository\TokenMysqlRepository'
  GuzzleHttp\Client: ~
  GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'
  PDO:
    class: PDO
    arguments:
      - 'mysql:host=%mysql.host%;dbname=%mysql.db%;charset=%mysql.charset%'
      - '%mysql.user%'
      - '%mysql.pass%'
      - { 3: 2, 19: 2, 20: false }
