parameters:
  beds24.apikey: '%env(BEDS24_APIKEY)%'
  beds24.token: '%env(BEDS24_DIGEST_TOKEN)%'
  beds24.props:
    156799: '%env(BEDS24_PROP_APARTMENTS)%'
    156424: '%env(BEDS24_PROP_GUESTHOUSE)%'
    156798: '%env(BEDS24_PROP_HOSTEL)%'
    159459: '%env(BEDS24_PROP_TEST)%'

  mysql.host: '%env(MYSQL_HOST)%'
  mysql.db: '%env(MYSQL_DB)%'
  mysql.user: '%env(MYSQL_USER)%'
  mysql.pass: '%env(MYSQL_PASS)%'
  mysql.charset: 'utf8mb4'

  rabbitmq.host: '%env(RABBITMQ_HOST)%'
  rabbitmq.port: '%env(RABBITMQ_DEFAULT_PORT, 5672)%'
  rabbitmq.user: '%env(RABBITMQ_DEFAULT_USER)%'
  rabbitmq.password: '%env(RABBITMQ_DEFAULT_PASS)%'

  sciener.app_id: '%env(SCIENER_APP_ID)%'
  sciener.lock_id: '%env(SCIENER_LOCK_ID)%'
  sciener.app_secret: '%env(SCIENER_APP_SECRET)%'
  sciener.user: '%env(SCIENER_USER)%'
  sciener.password: '%env(SCIENER_PASSWORD)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  App\Commands\RemoveExpiredPasscodes: ~    
  App\Controller\ApiController:
    arguments:
      - '@App\Services\BookingService'
      - '@App\Repository\BookingRepositoryInterface'
      - '@App\Services\LockService'
      - '@App\Services\Queue'
      - '%beds24.token%'
  App\Providers\Beds24\Client\ClientV1:
    arguments:
      - '@GuzzleHttp\ClientInterface'
      - '%beds24.apikey%'
  App\Providers\Sciener\Client\Client:
    arguments:
      - '@GuzzleHttp\ClientInterface'
      - '%sciener.app_id%'
      - '%sciener.lock_id%'
      - '%sciener.app_secret%'
      - '%sciener.user%'
      - '%sciener.password%'
  App\Queue\GetPasscodeHandler: ~
  App\Repository\BookingMysqlBookingRepository: ~
  App\Repository\BookingRepositoryInterface: '@App\Repository\BookingMysqlBookingRepository'
  App\Repository\LockMysqlRepository: ~
  App\Repository\LockRepositoryInterface: '@App\Repository\LockMysqlRepository'
  App\Repository\TokenMysqlRepository:
    arguments:
      - '@PDO'
  App\Repository\TokenRepositoryInterface: '@App\Repository\TokenMysqlRepository'
  App\Services\BookingService:
    arguments:
      - '@App\Providers\Beds24\Client\ClientV1'
      - '%beds24.props%'
  App\Services\LockService: ~
  App\Services\Queue: ~
  GuzzleHttp\Client: ~
  GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'
  PDO:
    class: PDO
    arguments:
      - 'mysql:host=%mysql.host%;dbname=%mysql.db%;charset=%mysql.charset%'
      - '%mysql.user%'
      - '%mysql.pass%'
      - { 3: 2, 19: 2, 20: false }
  PhpAmqpLib\Connection\AMQPStreamConnection:
    arguments:
      - '%rabbitmq.host%'
      - '%rabbitmq.port%'
      - '%rabbitmq.user%'
      - '%rabbitmq.password%'
